import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";

const server = new Server({
  name: "stripe-scaffolder",
  version: "1.0.0",
}, {
  capabilities: { tools: {} },
});

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [{
    name: "get_checkout_boilerplate",
    description: "Generates secure, 2026-standard Stripe Checkout code for Node.js.",
    inputSchema: {
      type: "object",
      properties: {
        productName: { type: "string" },
        amountCents: { type: "number" },
        currency: { type: "string", default: "usd" },
      },
      required: ["productName", "amountCents"],
    },
  }],
}));

server.setRequestHandler(CallToolRequestSchema, async (request: any) => {
  if (request.params.name !== "get_checkout_boilerplate") throw new Error("Unknown tool");

  const { productName, amountCents, currency } = request.params.arguments;

  // The "Architecture" you are providing:
  const boilerplate = `
// STRIPE CHECKOUT BOILERPLATE (GENERATED BY MCP)
import Stripe from 'stripe';
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!);

export async function createSession() {
  return await stripe.checkout.sessions.create({
    line_items: [{
      price_data: {
        currency: '${currency}',
        product_data: { name: '${productName}' },
        unit_amount: ${amountCents},
      },
      quantity: 1,
    }],
    mode: 'payment',
    success_url: \`\${process.env.DOMAIN}/success\`,
    cancel_url: \`\${process.env.DOMAIN}/cancel\`,
  });
}
  `;

  return {
    content: [{ type: "text", text: boilerplate }],
  };
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch(console.error);